DECLARE @thisDate DATE;

SET @thisdate = '{Position_Date}'

SELECT @thisdate;

DELETE TorViewBloombergPerSecurityPull;

INSERT TorViewBloombergPerSecurityPull
SELECT [SECURITIES],
       [BloombergErrorCode],
       [ID_BB_GLOBAL],
       [ID_BB_UNIQUE],
       [Name],
       [SECURITY_TYP],
       [EffectiveDate],
       [DL_SECURITY_TYPE],
       [DL_ASSET_CLASS],
       [ID_ISIN],
       [ID_CUSIP],
       [ID_BELGIUM],
       [ID_COMMON],
       [ID_DUTCH],
       [ID_FRENCH],
       [ID_LOCAL],
       [ID_SEDOL1],
       [ID_SEDOL2],
       [ID_SEDOL3],
       [ID_VALOREN],
       [ID_WERTPAPIER],
       [CRNCY],
       [POST_EURO_ID_ISIN],
       [PRE_EURO_ID_ISIN],
       [EQY_FUND_CRNCY],
       [ID_BB_PRIM_SECURITY],
       [ID_BB_PRIM_SECURITY_FLAG],
       [ADR_SH_PER_ADR],
       [COUNTRY],
       [COUNTRY_FULL_NAME],
       [DVD_CRNCY],
       [INDUSTRY_SECTOR],
       [SSR_LIQUIDITY_INDICATOR],
       [EQY_SH_OUT_REAL],
       [INDX_MWEIGHT],
       [LAST_TRADEABLE_DT],
       [AMT_ISSUED],
       [VOLUME_AVG_10D],
       [VOLUME_AVG_20D],
       [VOLUME_AVG_20D_CALL],
       [VOLUME_AVG_20D_PUT],
       [VOLUME_AVG_5D],
       [VOLUME_AVG_5D_CALL],
       [VOLUME_AVG_5D_PUT],
       [VOLATILITY_10D_CALC],
       [VOLATILITY_180D_CALC],
       [VOLATILITY_200D_CALC],
       [VOLATILITY_260D_CALC],
       [VOLATILITY_30D_CALC],
       [VOLATILITY_360D_CALC],
       [VOLATILITY_60D_CALC],
       [VOLATILITY_90D_CALC],
       [VOLATILITY_10D],
       [VOLATILITY_120D],
       [VOLATILITY_150D],
       [VOLATILITY_180D],
       [VOLATILITY_200D],
       [VOLATILITY_20D],
       [VOLATILITY_260D],
       [VOLATILITY_30D],
       [VOLATILITY_360D],
       [VOLATILITY_60D],
       [VOLATILITY_90D],
       [DELTA],
       [DELTA_ASK],
       [DELTA_BID],
       [DELTA_HEDGE_RATIO],
       [DELTA_LAST],
       [DELTA_MID],
       [DELTA_TM],
       [PX_CLOSE_2D],
       [PX_YEST_CLOSE],
       [QUOTE_TYP],
       [LAST_UPDATE],
       [LAST_UPDATE_DT],
       [PX_LAST_EOD],
       [PRIOR_CLOSE_ASK],
       [PRIOR_CLOSE_BID],
       [PRIOR_CLOSE_MID],
       [ULT_PARENT_CNTRY_DOMICILE],
       [ID_BB_ULTIMATE_PARENT_CO],
       [ID_BB_ULTIMATE_PARENT_CO_NAME],
       [BDVD_NEXT_EST_EX_DT],
       [BDVD_PROJ_DIV_AMT],
       [PX_ASK],
       [PX_BID],
       [PX_LAST],
       [PX_MID],
       [CUR_MKT_CAP],
       [HIGH_52WEEK],
       [LOW_52WEEK],
       [PREV_CLS_ASK_DISC],
       [PREV_CLS_MID_DISC],
       [PX_FIXING],
       [PX_HIGH],
       [PX_LOW],
       [PX_VOLUME],
       [YLD_YTM_MID]
FROM   [HELIUM].BloombergDataLicense.dbo.ve_BloombergPerSecurityPull
WHERE  effectivedate = @thisdate; 
