CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\dev\publish\Boss\BOSSUI"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\BossApps\BOSS Database Switch Tool\Boss Database Switch Tool"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\dev\Publish\BossApps\MilanMonthendProcess\MilanMonthendProcess"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\dev\Publish\BossApps\SettleDateModifier\SettleDateModifier"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\dev\Publish\BossApps\OptionValueManager\Option Value Manager"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\BossApps\TRecs\ReconciliationClient"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\BossApps\WireRequestForm\WireRequestForm"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\CreditApps\BasketEditor\BasketEditor"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\CreditApps\BondQuoteViewer\BondQuoteViewer"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\CreditApps\BondQuoteViewer2\BondQuoteViewer"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\CreditApps\ImpliedCorrelation\ImpliedCorrelation"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\CreditApps\IndexCapturer\IndexCapturer"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\CreditApps\Positions\Positions"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\CreditApps\RatingsCapturer\RatingsCapturer"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\GDE\GDE"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\Security Authorisation Test Harness\New\SecurityAuthorisationHarness"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\SFAnalyser\SFAnalyzer"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\TradeReporter\TradeReporter"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\VAR\FTPRM\FTP to RM app"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\VAR\GenericDataEditor\GenericDataEditing"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\VAR\RegCapInterface\RegCapInterface"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\VAR\VarInterface\VAR Interface"
CALL C:\Mage\MovePublishedApps.bat "\\DRFS1\data\Dev\Publish\BossTradeReporter\BossTradeReporter"
