USE [Bloomberg]

GO

/****** Object:  Table [dbo].[TorViewBloombergDescription]    Script Date: 28/10/2015 17:03:29 ******/
SET ANSI_NULLS ON

GO

SET QUOTED_IDENTIFIER ON

GO

SET ANSI_PADDING ON

GO

CREATE TABLE [dbo].[TorViewBloombergDescription]
  (
     [ADR_SH_PER_ADR]  [VARCHAR](255) NULL,
     [COUNTRY]         [VARCHAR](255) NULL,
     [DVD_CRNCY]       [VARCHAR](255) NULL,
     [ID_BB_UNIQUE]    [VARCHAR](255) NULL,
     [INDUSTRY_SECTOR] [VARCHAR](255) NULL,
     [PAR_AMT]         [VARCHAR](255) NULL,
     [TICKER]          [VARCHAR](255) NULL,
     [EFFECTIVEDATE]   [SMALLDATETIME] NULL
  )
ON [PRIMARY]

GO

SET ANSI_PADDING OFF

GO

CREATE CLUSTERED INDEX [CI_ID_BB_UNIQUE]
  ON [dbo].TorViewBloombergDescription ( [ID_BB_UNIQUE] ASC )
  WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
