USE [Bloomberg]

GO

/****** Object:  Table [dbo].[TorViewBloombergNorthAmericanPrice]    Script Date: 28/10/2015 17:04:09 ******/
SET ANSI_NULLS ON

GO

SET QUOTED_IDENTIFIER ON

GO

SET ANSI_PADDING ON

GO

CREATE TABLE [dbo].[TorViewBloombergNorthAmericanPrice]
  (
     [CNTRY_OF_DOMICILE]    [VARCHAR](255) NULL,
     [CRNCY]                [VARCHAR](255) NULL,
     [EQY_PRIM_EXCH]        [VARCHAR](255) NULL,
     [EQY_PRIM_EXCH_SHRT]   [VARCHAR](255) NULL,
     [EQY_SH_OUT]           [VARCHAR](255) NULL,
     [EQY_SH_OUT_REAL]      [VARCHAR](255) NULL,
     [EXCH_CODE]            [VARCHAR](255) NULL,
     [ID_BB_COMPANY]        [VARCHAR](255) NULL,
     [ID_BB_GLOBAL]         [VARCHAR](255) NULL,
     [ID_BB_UNIQUE]         [VARCHAR](255) NULL,
     [ID_CUSIP]             [VARCHAR](255) NULL,
     [ID_ISIN]              [VARCHAR](255) NULL,
     [ID_SEDOL1]            [VARCHAR](255) NULL,
     [ID_SEDOL2]            [VARCHAR](255) NULL,
     [LAST_UPDATE]          [VARCHAR](255) NULL,
     [NAME]                 [VARCHAR](255) NULL,
     [PRICING_SOURCE]       [VARCHAR](255) NULL,
     [PX_ASK]               [VARCHAR](255) NULL,
     [PX_BID]               [VARCHAR](255) NULL,
     [PX_LAST]              [VARCHAR](255) NULL,
     [PX_QUOTE_LOT_SIZE]    [VARCHAR](255) NULL,
     [SECURITY_TYP]         [VARCHAR](255) NULL,
     [TICKER_AND_EXCH_CODE] [VARCHAR](255) NULL,
     [EFFECTIVEDATE]        [SMALLDATETIME] NULL
  )
ON [PRIMARY]

GO

SET ANSI_PADDING OFF

GO

CREATE CLUSTERED INDEX [CI_TICKER_EXCH_CODE]
  ON [dbo].TorViewBloombergNorthAmericanPrice ( [TICKER_AND_EXCH_CODE] ASC )
  WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [NCI_ID_BB_UNIQUE]
  ON [dbo].TorViewBloombergNorthAmericanPrice ( [ID_BB_UNIQUE] ASC )
  WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [NCI_ID_BB_GLOBAL]
  ON [dbo].TorViewBloombergNorthAmericanPrice ( [ID_BB_GLOBAL] ASC )
  WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [NCI_ID_BB_COMPANY]
  ON [dbo].TorViewBloombergNorthAmericanPrice ( [ID_BB_COMPANY] ASC )
  WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
